/**
 * External links used throughout the application.
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by scripts/sync-links.js
 * To update links, modify the "links" section in package.json and run: pnpm sync-links
 */

export const LINKS = {
  DISCORD: "https://discord.com/invite/K2hmhfHRSt",
  GITHUB: "https://github.com/p4pupro/tabularis",
  X: "https://x.com/tabularisdb",
  BLUESKY: "https://bsky.app/profile/tabularis.bsky.social",
  MASTODON: "https://mastodon.social/@tabularis",
} as const;

// Named exports for convenience
export const DISCORD_URL = LINKS.DISCORD;
export const GITHUB_URL = LINKS.GITHUB;
export const X_URL = LINKS.X;
export const BLUESKY_URL = LINKS.BLUESKY;
export const MASTODON_URL = LINKS.MASTODON;
